author: 程明锐

keywords: '无心同学, 程明锐, 程明锐的独立博客, 程明锐的博客, 前端, 前端开发, 前端博客, javascript, ajax, nodejs, Vue，前端，技术，分享，学习，记录,个人成长，无心同学的个人博客|人生若只如初见，何事秋风悲画扇，偶尔努力，时常颓废的矛盾综合体，也不清楚自己喜欢什么，从小到大坚持最久的大概就是睡觉跟吃饭吧，但是很高兴与你在这里相遇。希望我们能一起进步'

description: 无心同学的个人博客|人生若只如初见，何事秋风悲画扇，偶尔努力，时常颓废的矛盾综合体，也不清楚自己喜欢什么，从小到大坚持最久的大概就是睡觉跟吃饭吧，但是很高兴与你在这里相遇。希望我们能一起进步

# 导航栏头部名称
nav_name: 无心

# 导航栏座右铭
motto: "人生若只如初见，何事秋风悲画扇"

github: "https://github.com/CasualMing"

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# 一言 采用个人接口 https://api.imjad.cn/hitokoto.md
oneSay:
  istrue: true
  cat: Novel   # a	Anime - 动画 b	Comic - 漫画 c	Game - 游戏 d	Novel - 小说 e	原创 f	来自网络 g	其他 ，参数不传就是任意
  charset: utf-8    # string 返回字符集，支持 gbk/utf-8  默认utf-8
  length: 1000  # int 返回一句话的长度限制，超出则打断并添加省略号
  encode: json   #string 返回数据格式，js:返回脚本，jsc：返回指定函数名的回调函数。空：返回纯文本。默认 json 
  fun: sync # string 异步调用时，指定 CallBack 的函数名
  source: #int 值为 0 获取「系统收录」，为 1 获取「我的一言」 不填就是随机

# APalyer音乐
aplayer:
  isplay: true
  api: "https://api.uomg.com/api/rand.music"
  sort: "抖音榜"     #选择输出分类[热歌榜|新歌榜|飙升榜|抖音榜|电音榜]，为空输出热歌榜
  format: "json"  #	选择输出格式[json|mp3]

# RSS文件位置
rss: 

# 自定义样式文件
custom_styles: 

# 自定义脚本文件
custom_scripts: 

# 代码高亮主题: normal | night | night blue | night bright | night eighties
highlight_theme: "night eighties"

# 开启数学公式渲染
mathjax: true

copyright:
  enable: true
  author: "程明锐"
  show_link: true
  more: '版权声明: 本博客所有文章除特别声明外, 均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 许可协议. 转载请注明出处!'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2019-03-10"

# 如何开启 评论&统计
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: ry19ixO4PYVKU8xjTT8OHLXz-gzGzoHsz # 填写您的appid
  appkey: QGAGLMNyXwP4YtI0e4tqP9sK # 填写您的appkey
  comment: true # 是否开启评论系统
  count: true # 是否开启文章统计

# 需要保证leancloud.comment为true
welcome: 
  enable: true
  interval: 30

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
passwords: 
  - f3510ec0e231838f25a339252def6d28bd56d7d800351bf23d93e7ab57ed90cd # wuxintongxue

share:
  twitter: false
  facebook: false
  weibo: false
  qq: false
  wechat: false

analytics:
  baidu:
    enable: true
  google:
    enable: true
    id: UA-135904732-1
  "360": 
    enable: true
    id: fb4414f62705e5c12acc6546eb179624

reward:
  -
    src: /images/wechat.png
    alt: "WeChat"
  # -
  #   src: /images/alipay.png
  #   alt: "AliPay"

nav:
  -
    name: "首页"
    path: "/"
  -
    name: "收藏的工具文章"
    path: "/passages/note/优秀文章列表/"
  -
    name: "API"
    path: "/passages/react/收集各种实用api/"
  - 
    name: "归档"
    path: "/archives/"
  -
    name: "标签"
    path: "/tags/"
  -
    name: "分类"
    path: "/categories/"
  -
    name: "友链"
    path: "/friends/"
  -
    name: "关于"
    path: "/about/"
  -
    name: "相册"
    path: "/photo/"

footer:
  - 
    title: "博客推荐"
    children:
      - 
        name: "无心"
        path: "https://wuxin.netlify.com/"
      - 
        name: "阮一峰的个人网站"
        path: "http://ruanyifeng.com/"
  -
    title: "系列笔记"
    children:
      -
        name: "重学前端系列笔记"
        path: "/categories/重学前端系列笔记/"
      -
        name: "React系列学习笔记"
        path: "/categories/react学习记录/"
      -
        name: "收藏的API"
        path: "/passages/react/收集各种实用api/"
      -
        name: "收藏的工具以及优秀文章"
        path: "/passages/note/优秀文章列表/"
  -
    title: "逃窜之地"
    children: 
      -
        name: "语雀"
        path: "https://www.yuque.com/wuxintomgxue"
      -
        name: "github"
        path: "https://github.com/CasualMing"

footer_contact: "Email: 18327866033@163.com"

friends_avatar_cdn: 
friends:
  -
    nickname: GodBMW
    avatar: https://gravatar.loli.net/avatar/b20750c40cd911256ddbd76a7f7e724c
    site: https://godbmw.com/
    meta: 主题作者
    show: true
  - 
    nickname: 石璞东
    avatar: /images/dong.jpg
    site: http://www.shipudong.com
    meta: 要学会哈哈哈
    show: true
  - 
    nickname: 钻芒博客
    avatar: https://www.zmki.cn/wp-content/uploads/2019/02/zmki-favicon-.png
    site: https://www.zmki.cn/
    meta: 记录自己平时的学习&生活，html、Photoshop、Pr、办公基础套件大全（善用Excel函数） 
            PHP、MySQL、JavaScript半吊子选手，学习充电中..
    show: true     
  - 
    nickname: 飞鱼慕鸟
    avatar: https://view.moezx.cc/images/2019/05/27/example-97783.jpg
    site: https://www.feiyumn.com
    meta: 浮水飞鱼，空慕青鸟。喜欢二次元的废材PHPer
    show: true
  - 
    nickname: Krryblog
    site: https://ainyi.com
    meta: 你的美好，我都记得
    avatar: https://raw.githubusercontent.com/Krryxa/WORK-LEARNING/master/images/ico.jpg
    show: true