author: 程明锐

keywords: '程明锐, 程明锐的独立博客, 程明锐的博客, 前端, 前端开发, 前端博客, javascript, ajax, nodejs, Vue，前端，技术，分享，学习，记录,个人成长，程明锐的个人网站|人生若只如初见，何事悲风秋画扇，偶尔努力，时常颓废的矛盾综合体，也不清楚自己喜欢什么，从小到大坚持最久的大概就是睡觉跟吃饭吧，但是很高兴与你在这里相遇。希望我们能一起进步'

description: 程明锐的个人网站|人生若只如初见，何事悲风秋画扇，偶尔努力，时常颓废的矛盾综合体，也不清楚自己喜欢什么，从小到大坚持最久的大概就是睡觉跟吃饭吧，但是很高兴与你在这里相遇。希望我们能一起进步

# 导航栏头部名称
nav_name: 无心

# 导航栏座右铭
motto: "人生若只如初见，何事悲风秋画扇"

github: "https://github.com/CasualMing"

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss: 

# 自定义样式文件
custom_styles: 

# 自定义脚本文件
custom_scripts: 

# 代码高亮主题: normal | night | night blue | night bright | night eighties
highlight_theme: "night eighties"

# 开启数学公式渲染
mathjax: true

copyright:
  enable: true
  author: "程明锐"
  show_link: true
  more: '版权声明: 本博客所有文章除特别声明外, 均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 许可协议. 转载请注明出处!'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2019-03-10"

# 如何开启 评论&统计
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: ry19ixO4PYVKU8xjTT8OHLXz-gzGzoHsz # 填写您的appid
  appkey: QGAGLMNyXwP4YtI0e4tqP9sK # 填写您的appkey
  comment: true # 是否开启评论系统
  count: true # 是否开启文章统计

# 需要保证leancloud.comment为true
welcome: 
  enable: true
  interval: 30

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
passwords: 
  - efe07af7441da2b69c4a41e42e73be4db47f66010a56900788a458354a7373ec # godbmw

share:
  twitter: false
  facebook: false
  weibo: true
  qq: false
  wechat: false

analytics:
  baidu:
    enable: true
  google:
    enable: true
    id: UA-135904732-1
  "360": 
    enable: true
    id: fb4414f62705e5c12acc6546eb179624

reward:
  -
    src: /images/wechat.png
    alt: "WeChat"
  # -
  #   src: /images/alipay.png
  #   alt: "AliPay"

nav:
  -
    name: "首页"
    path: "/"
  -
    name: "归档"
    path: "/archives/"
  -
    name: "标签"
    path: "/tags/"
  -
    name: "分类"
    path: "/categories/"
  -
    name: "友链"
    path: "/friends/"
  -
    name: "关于"
    path: "/about/"

footer:
  - 
    title: "博客推荐"
    children:
      - 
        name: "GodBMW"
        path: "https://godbmw.com/"
      - 
        name: "阮一峰的个人网站"
        path: "http://ruanyifeng.com/"
  -
    title: "系列笔记"
    children:
      -
        name: "重学前端系列笔记"
        path: "https://wuxin.netlify.com/categories/%E9%87%8D%E5%AD%A6%E5%89%8D%E7%AB%AF%E7%B3%BB%E5%88%97%E7%AC%94%E8%AE%B0/"
  -
    title: "抓到我"
    children: 
      -
        name: "语雀"
        path: "https://www.yuque.com/wuxintomgxue"
      -
        name: "github"
        path: "https://github.com/CasualMing"

footer_contact: "Email: 18327866033@163.com"

friends_avatar_cdn: 
friends:
  -
    nickname: GodBMW
    avatar: https://gravatar.loli.net/avatar/b20750c40cd911256ddbd76a7f7e724c
    site: https://godbmw.com/
    meta: 主题作者
    show: true
  - 
    nickname: 石璞东
    avatar: /images/dong.jpg
    site: http://www.shipudong.com
    meta: 要学会哈哈哈
    show: true